### DISCUSSION TITLE
Changing the front page

### DISCUSSION THREAD

**Discussion by GEEOSDGs** [open-sdg/open-sdg#1657] [Q&A] [answered]
Hello, we were suggested to post our questions here.
We have a GitHub account and created the OpenSDG template. We are trying to make some configurations to the template, and we are having the following challenges:
1. Removing the front/cover page - we would like the homepage to be the first page of the SDG dashboard - we are not finding the location of the file under our GitHub account, and, we do not know how to delete it.
For example, our current website's homepage is this:
![image](https://user-images.githubusercontent.com/91685072/172700024-46dfb074-0536-4ab2-8106-17d62a35d440.png)
We would like to delete it so we go directly to the "goals page":
![image](https://user-images.githubusercontent.com/91685072/172701563-2874b15a-fbe4-421f-b142-8abbabe88520.png)

2. Accessing the "goals page" to change the title.
Currently it says "Goals":
![image](https://user-images.githubusercontent.com/91685072/172703480-20ea51b6-5c41-4e1b-a539-828112555ac6.png)

3. Configuring the targets and indicators page to two columns instead of one column, similar to how Bristol's dashboard is set up.
![image](https://user-images.githubusercontent.com/91685072/172704112-98abf549-cee7-4fce-bdc3-28b4381a6376.png)

4. Hiding the edit tab.
![image](https://user-images.githubusercontent.com/91685072/172704445-bffee774-4896-436a-8ba8-d140ee1e8fc4.png)

**Comment by brockfanning** [comment, marked as answer]
@GEEOSDGs I think I can answer some of these. I'll try to put each answer in a separate post.

Starting with the first question - how to use the "goals" layout as the front page of the site?

One of the site configurations in Open SDG is [create_pages](https://open-sdg.readthedocs.io/en/latest/configuration/#create_pages) - this setting is intended to simplify things by creating certain commonly-used pages, including the front page. The setting should be a list of pages, each of which will be created for you. For example, here is the `create_pages` that is in the "site starter" at the time of this writing:

```
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
```

In this case the first item (the one with a "folder" of `/` and a "filename" of `'') is the front page.  If you would like to use a different layout for your front page, you could change the "layout" of this item. For example, if you want to use the "goals" layout, you could change it to:

```
create_pages:
  - filename: ''
    folder: /
    layout: goals
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
```

So in short, the way to accomplish what you're looking for is to update your `create_pages` site configuration so that the front page is using the `goals` layout.

**Comment by brockfanning** [comment]
@GEEOSDGs I think I can answer some of these. I'll try to put each answer in a separate post.

Starting with the first question - how to use the "goals" layout as the front page of the site?

One of the site configurations in Open SDG is [create_pages](https://open-sdg.readthedocs.io/en/latest/configuration/#create_pages) - this setting is intended to simplify things by creating certain commonly-used pages, including the front page. The setting should be a list of pages, each of which will be created for you. For example, here is the `create_pages` that is in the "site starter" at the time of this writing:

```
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
```

In this case the first item (the one with a "folder" of `/` and a "filename" of `'') is the front page.  If you would like to use a different layout for your front page, you could change the "layout" of this item. For example, if you want to use the "goals" layout, you could change it to:

```
create_pages:
  - filename: ''
    folder: /
    layout: goals
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
```

So in short, the way to accomplish what you're looking for is to update your `create_pages` site configuration so that the front page is using the `goals` layout.
