### DISCUSSION TITLE
data_start_values initial values of the same disaggregation

### DISCUSSION THREAD

**Discussion by SandraMarq** [open-sdg/open-sdg#2065] [Q&A] [answered]
Hello

How do you configure the data_start_values tag for multiple starts in the same disaggregation?

Thank you

**Comment by SandraMarq** [comment, marked as answer]
Hello

I already found the way.

I'm sharing it in case anyone else needs it.

![image](https://github.com/open-sdg/open-sdg/assets/118024145/241e57a2-c0d6-464b-a36c-ce8c5122d430)

**Reply by sarah-beasley** [reply]
Thanks, that's really helpful!

**Reply by brockfanning** [reply]
Does this really work? I am surprise if so -- I would have thought it should be:

```
data_start_values:
  - field: Poblacion en pobreza_nacional
    value: Nacional
  - field: Poblacion en pobreza_nacional
    value: Hombres
  - field: Poblacion en pobreza_nacional
    value: Mujeres
```

**Reply by TedTansley** [reply]
I have been trying like: 
```
data_start_values:
  - field: Poblacion en pobreza_nacional
    value: Nacional
  - field: Poblacion en pobreza_nacional
    value: Hombres
  - field: Poblacion en pobreza_nacional
    value: Mujeres
```

But I can't get any of the values to show as the default chart visual. It ends up only showing "This data is not available. Please choose alternative data to display."
