### ISSUE TITLE
data_start_values does not support blanks in value

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1172]
**Please complete the following information**
Data repository URL: https://github.com/WohnungNDS/WK_Data
Data or metadata issue: metadata
Input format: CSV

**Describe the bug**

Using this

```
data_start_values:
  - field: Gebietseinheit
    value: Niedersachsen
  - field: Aufenthaltstitel
    value: Duldung
```
works fine

Using This

```
data_start_values:
  - field: Gebietseinheit
    value: Niedersachsen
  - field: Aufenthaltstitel
    value: Geflüchtete und geduldete Personen insgesamt
```
has no effect.

https://wohnungnds.github.io/WK_Site/11-1-1/

[metadata](https://github.com/WohnungNDS/WK_Data/blob/develop/meta/11-1-1.md)
[data](https://github.com/WohnungNDS/WK_Data/blob/develop/data/indicator_11-1-1.csv)
