### ISSUE TITLE
Set data_start_values / Sub-categories by Series?

### ISSUE THREAD

**Issue by EFT-Defra** [open-sdg/open-sdg#1176]
Hi all,

Is this possible? Because, if it is, I haven't be able to get it to work.

Basically, I've got an indicator with two Series and I want to set the starting Sub-categories for each. I can get the two Series to display fine, so I know that's not part of the problem. I've tried the following without success, they all return blank spaces where the chart and Series / Sub-categories panel should be:

Setting all the starting values:
```
data_start_values:
  - field: Disaggregation-field-in-Series-1
    value: Apple
  - field: Disaggregation-field-in-Series-1
    value: Orange
  - field: Disaggregation-field-in-Series-2
    value: Cat
  - field: Disaggregation-field-in-Series-2
    value: Dog
```

Setting all the starting values for one series and setting that series as a starting value (as mentioned in #354):
```
data_start_values:
  - field: Series
    value: Series-1-name
  - field: Disaggregation-field-in-Series-1
    value: Apple
  - field: Disaggregation-field-in-Series-1
    value: Orange
```

Using the [graph_titles syntax](https://open-sdg.readthedocs.io/en/latest/metadata-format/#note-about-unit-specific-and-series-specific-settings) (though I had no reason to believe this would work):
```
data_start_values:
  - series: Series-1-name
    field: Disaggregation-field-in-Series-1
    value: Apple
  - series: Series-1-name
    field: Disaggregation-field-in-Series-1
    value: Orange
  - series: Series-2-name
    field: Disaggregation-field-in-Series-2
    value: Cat
  - series: Series-2-name
    field: Disaggregation-field-in-Series-2
    value: Dog
```

Any ideas?

**Comment by LucyGwilliamAdmin** [comment]
@EFT-Defra if I understand what you're looking for correctly, it's now possible with 1.4.0.
For example, I used
```
data_start_values:
  - series: 1) Woodland area net change
    field: Country
    value: England
  - series: 1) Woodland area net change
    field: Country
    value: Wales
  - series: 5) Woodland area under certification scheme
    field: Country
    value: England
  - series: 5) Woodland area under certification scheme
    field: Country
    value: Wales
```

to get England and Wales as starting values for two different series here:
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-start-values-test/15-2-1/
