### ISSUE TITLE
Control graph type by series

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1283]
Make it possible to control graph type by series e.g. the following should mean the graph type is changed when the series is changed:

```
graph_type:
  - series: Series 1
    type: line
  - series: Series 2
    title: bar
```

From #1176
