### ISSUE TITLE
Map initial display error

### ISSUE THREAD

**Issue by RobertSDG** [open-sdg/open-sdg#1362]
**Please complete the following information** 
Site repository URL: https://github.com/sdg-bristol/sdg-site-bristol develop branch
Data repository URL: https://github.com/sdg-bristol/sdg-data-bristol
Open SDG version: 1.5.0

**Describe the bug**
The map initially shows Africa rather than the ward data added to the platform which is in Bristol.
The data is displayed on the map however if panned over to and zoomed in manually.

**To Reproduce**
1. Go to https://sdg-bristol.github.io/sdg-site-bristol/9-c-1/
2. Go to "maps" tab
3. The map loads and displays Africa

**Expected behavior**
The map to be centred on any ward in Bristol at a zoom level that allows data to be observed

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 64 bit (version 1909)
 - Browser: Edge (chromium based) 64-bit
 - Version: 94.0.992.31

**Comment by LucyGwilliamAdmin** [comment]
@RobertSDG thanks for raising issue here.

So firstly I would definitely try to reduce the ward geojson down to just the wards that you need (i.e. those in Bristol). There may be a filtered version available online that you can point at but if not it is quite straightforward to do it manually but I also tried it out [here](https://github.com/LucyGwilliamAdmin/sdg-data-bristol/tree/develop/geojsons) if you want to just take that. If you go down that route, you will need to upload the file to your data repo and then point at that. For example in my example, in my data config file I'm pointing at `geojsons/Bristol_Wards_(December_2020)_UK_BGC_V2.geojson`

After you've done that, I'd try to simplify the site config map options for now.. something like:
```
map_options:
  tileURL: https://{s}.tile.jawg.io/{id}/{z}/{x}/{y}{r}.png?access-token={accessToken}
  tileOptions:
    id: jawg-light
    accessToken: 6D21hTioQUEfcuV4EEEg1UH4W98hoHu4k832Jdod3KqX9DMM2yClAkc8Zfs7XPKg
    attribution:  <a href="http://jawg.io" title="Tiles Courtesy of Jawg Maps" target="_blank">&copy; <b>Jawg</b>Maps</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | <a href="http://geoportal.statistics.gov.uk/">ONS</a>
  minZoom: 4
```

Hopefully you can work up from there then.
