### ISSUE TITLE
No problem @WohnungNDS

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1394]
No problem @WohnungNDS 

For `minZoom` and `maxZoom` under map_options, that controls the total minimum/maximum zoom, no matter what layer is displayed

`min_zoom` and `max_zoom` under map_layers, tells the map what layer to show.

For example if you have
```
map_options:
  minZoom: 0
  maxZoom: 10
```

you may want:
```
map_layers:
-  subfolder: maps
    label: indicator.map
    min_zoom: 6
    max_zoom: 10
    staticBorders: false
-  subfolder: worldmap
    label: indicator.map
    min_zoom: 0
    max_zoom: 5
    staticBorders: false
```

This would create a nested zoom functionality where if data for both layers is available on an indicator, the 'worldmap' layer would show when zoomed out to the max and until you zoom in 6 times. Once you zoom in 6 times or more, the 'maps' layer would show until you get to zoom 10. Once you get to zoom 10 you won't be able to zoom in any more.

Note: all `min_zoom`s should be greater than `minZoom` and all `max_zoom`s should be less than `maxZoom`

_Originally posted by @LucyGwilliamAdmin in https://github.com/open-sdg/open-sdg/issues/1213#issuecomment-854851356_
