### ISSUE TITLE
Dynamically populate Units footer fields with data column values

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1549]
#1484 allows for footer fields to be configured on an indicator-by-indicator basis (including limiting to a specific series or units).

However, where possible these fields should be populated using the data. For example, if a CSV has a Units column, the values in this column will be used to populate the Unit of measure footer field and it would change dynamically when a toggle option is changed.

**Comment by LucyGwilliamAdmin** [comment]
I'm not sure of the best way to do this as the functionality with #1484 means that the default footer fields will get replaced. One option is that there is:

A site-wide config option is used to set default footer fields which will show for every indicator e.g.
```
footer_fields:
  - field: computation_units
    label: Unit of measurement
  - field: source_organisation
    label: Source
  - field: geographical_coverage
    label: Geographical area
  - field: data_footnote
    label: Footnote
  - field: additional_field_1
    label: New field
```

Then the indicator config would work as follows:
- If no value is set in the metadata, the field will fall back on what is in the corresponding column in the data. Perhaps there should be a config option for this somewhere, so in the case where someone uses SDMX they could for example say map data_footnote to COMMENT_TS
- If setting for whole indicator the fields would just be set as normal e.g.
  `computation_units: Percentage (%)`
- If setting for specific series or units, then the usual syntax will be used e.g.
    
    ```
    footer_fields:
      - unit: percentage
        value: Percentage (%)
    ```

@phillipgardiner where I say
> A site-wide config option is used to set default footer fields which will show for every indicator 

If a value isn't set for the field, should the field still show with no value? I.e. does this come back to 'users might wonder why the field is on some indicators but not others'? (but obviously data detectives should fill them in with at least something)

@brockfanning I think what I've explained above may undo some of the work done in #1484?

@phillipgardiner @otis-bath @brockfanning @AnnCorp what are your thoughts? Will also raise in today's tech call if we have time
