### ISSUE TITLE
Remove mandatory items from `create_pages` site config

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1595]
Right now, the `create_pages` site config setting is expected to have items for `/indicators.json` and `/search` -- both of which are needed for the search functionality. There is no reason (that I can think of) that an implementation of Open SDG would *not* want these items created. So, rather than having them needed as part of the user-controlled `create_pages` setting, they should be automatically created regardless of what is in the `create_pages` setting. This will simplify the site config a bit, and removes the possibility that a user might accidentally mess up the search functionality by removing those items.

For example, right now the config for `create_pages` in the site starter is this:

```
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
```

But if we automate the `/indicators.json` and `/search` items, it would just be this:

```
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /goals
    layout: goals
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
```
