### ISSUE TITLE
Translation of 'Year' needs including in Open SDG

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1634]
Nazira from Kyrgyzstan recently flagged that 'Year' is not translated properly on their NRP, checking the Armenian platform the same issue has occurred so a wider Open SDG fix would be useful. 
https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/1-1-1/
https://armstat.github.io/sdg-site-armenia/ru/1-1-1/

**Comment by brockfanning** [comment]
@otis-bath This should be resolved now if pointing to the latest sdg-translations code (2.0.0-dev) in the data config file. For example:

```
translations:
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: 2.0.0-dev
  - class: TranslationInputYaml
    source: translations
```

The approach I used was to add a new "data" translation group in sdg-translations: https://hosted.weblate.org/projects/sdg-translations/data/. Open SDG automatically uses a "data" group to translate any data-related text, so no changes to Open SDG were needed.
