### ISSUE TITLE
Throw error if metadata_tabs site config is not in correct format

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1648]
The `metadata_tabs` is another site config that might be in a deprecated structure in some sites using older versions of Open SDG. In 2.0.0 we should throw a helpful error message if it is not in the right structure.

To add some detail: the older syntax was from 1.1.0, and looked like this:

```
metadata_tabs:
  national:
    title: indicator.national_metadata
    blurb: indicator.national_metadata_blurb
  global:
    title: indicator.global_metadata
    blurb: indicator.global_metadata_blurb
  sources:
    title: indicator.sources
    blurb: ''
```

Whereas the current syntax (since 1.2.0) is:

```
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
```
