### ISSUE TITLE
data_start_values for units have no effect

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#1888]
**Please complete the following information** 
Site repository URL: (https://github.com/christoph-LSN/MT_Site)
Data Repo URL: https://github.com/christoph-LSN/IM_Data
Open SDG version: [e.g. 2.1.0]

**Describe the bug**
setting data_start for units values have noeffect. Seeting data_start_value to "%" doesnot shows "%" but Anzahl instead

example meta file: https://github.com/christoph-LSN/IM_Data/edit/develop/meta/3-1-3.md
example indicator: https://christoph-lsn.github.io/MT_Site/3-1-3/

````
data_start_values:
  - unit: "%"
    field: Gebietseinheit
    value: Niedersachsen
  - unit: "%"
    field: Kinderbetreuung
    value: Kinder im Alter von unter 3 Jahren mit ausländischer Herkunft mindestens eines Elternteils
  - unit: "%"
    field: Kinderbetreuung
    value: Kinder im Alter von 3 bis unter 6 Jahren mit ausländischer Herkunft mindestens eines Elternteils
````

**Screenshots**
![image](https://user-images.githubusercontent.com/94443931/205889827-ec83e95d-3362-4d95-b699-7a6a507d6735.png)

@LucyGwilliamAdmin I have asked this question earlier here: #1453 At that time it works....
I also have in my mind that @MoBosse has the similar issue longer time ago, but I cannot find it anymore

**Comment by brockfanning** [comment]
@christoph-LSN That's an interesting point - I believe when you set "unit" in that configuration, that you are saying that *when that unit is active* you want those fields to be the defaults. You can test this by switching to "%" manually on the indicator page. I believe you should see your start values selected already when you manually switch to "%".

But it sounds like you are instead wanting to start with "%" already selected. I'll do a little testing and see if there is some way to do that.

**Comment by christoph-LSN** [comment]
@brockfanning, yes I would like to see the % values when the indikator is visitited the first time.
Thank you for looking in it!

**Comment by brockfanning** [comment]
@christoph-LSN Have you tried setting a field called "Units"? For example:

```
data_start_values:
  - field: Units
    value: %
```

In theory that should make it start with percentage selected.

**Comment by christoph-LSN** [comment]
@brockfanning I am not in my office for a couple of weeks.. I will try it lately in the end of April

**Comment by brockfanning** [comment]
@christoph-LSN I wanted to follow up on this, because I recently looked into the `data_start_values` code and have a better understanding now. As mentioned above, what you can do here is something like this:

```
data_start_values:
  - field: Units
    value: %
```

I also wanted to make clear that the `data_start_values` setting does not support the functionality where you specify a "unit" or "series" property. I speculated about that above, but I was wrong - it does not support this. So, for example, in the following:

```
data_start_values:
  - unit: "%"
    field: Gebietseinheit
    value: Niedersachsen
```

...the `unit` property above does not have any effect. It is essentially the same as doing:

```
data_start_values:
    field: Gebietseinheit
    value: Niedersachsen
```
