### ISSUE TITLE
Metadata validation fails on date fields

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1958]
When the indicator metadata contains a field that is formatted like a date, the automatic validation fails. For example, if an indicator has this in its metadata:

```
my_date_field: 2021-04-01
```

And the metadata schema (eg, _prose.yml) includes this:

```
      - name: "my_date_field"
        field:
          element: hidden
          label: "My date field"
          translation_key: "My date field"
          scope: national
```

Then the check_data.py script will fail with this output:

```
- My date field (allOf/0/my_date_field): datetime.date(2021, 4, 1) is not of type 'string', 'integer', 'number', 'boolean', 'null'
```

The problem appears to be that the YAML parser converts "2021-04-01" into a Python datetime object, but the validator for the metadata schema is looking for a string, integer, number, boolean, or null.

I believe to fix this we would need to either:
1. Get the YAML parser to not convert things into datetime objects, or
2. Get the metadata schema to also look for datetime objects
