### ISSUE TITLE
Can't edit metadata tab label

### ISSUE THREAD

**Issue by Jonkat323** [open-sdg/open-sdg#1986]
Site repository URL: https://github.com/COJ-SDG/site

I am struggling to change the metadata tab label. For example, I want to change the default "National Metadata" to "COJ Metadata".

I have tried to edit the metadata_tabs section of the _config.yml file without luck.

I did create a Q&A discussion for this but have not received any replies.

**Comment by Govej** [comment]
Hi again,

I've just tested the config changes on our UK site, I can see in your config that the metadata tabs section was included but currently at least doesn't have any customisation. Please feel free to copy paste the code snippet below to use, I've included some screenshots of what these changes displayed on our testing site and a link to it

```
metadata_tabs:
  - scope: national
    title: "COJ Metadata"
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
```
![image](https://github.com/open-sdg/open-sdg/assets/77059178/e0e81f7c-9d5b-48f4-b5a6-6fde7681a588)

![image](https://github.com/open-sdg/open-sdg/assets/77059178/23e5cccc-f858-48a0-8a79-f7e571be6e68)

http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-metadata-tabs-test/3-1-1/
