### ISSUE TITLE
changing metadata fields

### ISSUE THREAD

**Issue by christoph4711** [open-sdg/open-sdg#339]
@brockfanning 

How do I change the number and caption of the global metadata fields? I only need about five or six metadata fields. Perhaps I also want to change the name "global metadata" to anything else.

The caption I'think i change with adding a metadata_fields.yml in my translations folder, but where do I change the number of the fields?

And how do I hide the National Metadata?

**Comment by LucyGwilliamAdmin** [comment]
@christoph4711 I'm not entirely sure what you're trying to do? Could you maybe do a mock-up for what the Global metadata tab would look like?

As for hiding the National Metadata tab, I think this is something the UK wants to do when all of the fields inside it are empty, similarly with Sources tab. Also we would like to hide fields which have no value.

**Comment by christoph4711** [comment]
@LucyGwilliamAdmin 
I want only a cpuple of fields like
Global Metadata
     - Indicator description:
     - Methods:
     - further informations:
     - Used Data:
     - tbc

and then hiding the national metadata and the data source

I also can use the national meta data for that and hiding the global meta data

**Comment by LucyGwilliamAdmin** [comment]
I feel like what might be better is if we add the ability to hide the existing metadata tabs as they are and then add ability to add own tab in metadata area with configurable field names.
@christoph4711 @brockfanning what are your thoughts?

**Comment by christoph4711** [comment]
To my mind this would be great. Pheraps thinking about different or adjustible field lengths. In my case eg the indicator description may be cover two or three hundred words.

**Comment by brockfanning** [comment]
Maybe a site config variable called `metadata_tabs`? Something like this:

```
metadata_tabs:
  -  name: Global metadata
     fields:
       - indicator_name
       - indicator
       - target
       - target_id
       - etc...
  - name: National metadata
    fields:
      - indicator_name_national
      - national_geographical_coverage
      - etc....
```

There could also be a setting like this:
```
hide_empty_metadata: true
```
For sites that would prefer not to see empty fields.
