### ISSUE TITLE
Pre selection dissagrergation /sub-categories

### ISSUE THREAD

**Issue by christoph4711** [open-sdg/open-sdg#354]
I 've observed tha in the dissaggregation dropdown always the first item is selected. In my use case I want to preselect another one (Niedersachsen), which is not on the first item in thedissaggregation  dropdown. Is there a possibility to do this? Something like "default-selection"?

**Comment by brockfanning** [comment]
@christoph4711 There is some existing code that handle that, but I'm realizing that its documentation is in an unexpected place: see the bit about `data_start_values` [here](https://open-sdg.readthedocs.io/en/latest/data-format/#indicators-without-headlines). Can you give this a try and see if it works? We definitely need to add some tests and better documentation around this.

Note I think you would also want to add a new field in your data repository's `_prose.yml` file. Something like this (but with different "options" though):
```
      - name: "data_start_values"
        field:
            scope: data
            element: multiselect
            label: "Starting values"
            options:
              - name: 'Apple'
                value: 'Apple'
              - name: 'Orange'
                value: 'Orange'
```

**Comment by christoph4711** [comment]
@brockfanning 
Thanks a lot! it works... I think about to add a new field to the _prose.yml

**Comment by LucyGwilliamAdmin** [comment]
I'm not entirely sure what this does? Just curious in case it's something we want to use.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This is for indicators that don't have headlines. The feature is to allow control over what disaggregations are selected when the indicator first loads. Here's an example of a use-case: let's say an indicator is intended to highlight a gender gap. In that case you really want it to start off with both "Female" and "Male" selected, so that the user can immediately see the gender gap. So, you put this in the metadata:
```
data_start_values:
  - Female
  - Male
```

**Comment by LucyGwilliamAdmin** [comment]
Ah right, that will come in useful. Thanks for explaining. Is there something similar to choose a start units type?

**Comment by brockfanning** [comment]
No, we never added a feature for a stating unit (I imagine it would be `data_start_unit`?) though that would definitely make sense.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning just came across this again and think we may have use for it - what would actually be under the options (where Apple and Orange are)?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe I tried this recently and it actually works to use "Units" in the [data_start_values field](https://open-sdg.readthedocs.io/en/latest/metadata-format/#starting-values). For example:

```
data_start_values:
  - field: Fruit
    value: Apples
  - field: Grade
    value: A
  - field: Units
    value: Percentage
```

Can you confirm? If it works, I think we can close this.
