### ISSUE TITLE
Override metadata fields per unit of measurement

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#578]
As we've been adding features we have noticed a recurring need to have some functionality behave differently for each unit of measurement. For example, we recently added a `graph_titles` feature to allow different titles per unit of measurement. Just throwing out an idea for a more future-proof way to do that, like:

```
unit_overrides:
    - unit: Percent
       graph_title: My percentage title
       data_footnote: My percentage footnote
       etc...
```

It's not totally clear that this is necessary at this time, but I wanted to document the idea in case it's useful later.
