### ISSUE TITLE
Map funtionality

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#769]
Hi @brockfanning, 

i have tried to use the map option - but something went wrong as cou can see [here](https://wohnungnds.github.io/WK_Site/1-1-1/)

I am not sure if I understand the docs right:

I put my geojson file in the data repsoitroy [/geojson/maps](https://github.com/WohnungNDS/WK_Data/tree/develop/geojson/maps) and added the following code in my [config ](https://github.com/WohnungNDS/WK_Site/blob/develop/_config.yml) file

```
map_options:
  minZoom: 5
  maxZoom: 10
  tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:  
    id: mapbox.light
    accessToken: pk.eyJ1IjoiY2hyaXN0b3BoNDcxMSIsImEiOiJjanp1cjdpbzQwMTFwM29tdzJ2ZTh3Ymo4In0.C7_7e3AFcMaF_QBg6MaT0Q
    attribution: <a href="https://www.mapbox.com">Mapbox</a> | <a href="http://www.bkg.bund.de">© GeoBasis-DE / BKG</a>
```

 
```

map_layers:
    subfolder: maps
    # The label to use in the "Download GeoJSON" button:
    label: indicator.map
    # The minimum zoom at which this layer should be visible.
    min_zoom: 0
    # The maximum zoom at which this layer should be visible.
    max_zoom: 20
    # Whether or not these boundaries should display statically on lower layers.
    staticBorders: false
```
But the map will not appear....
Do you have any idea?

**Comment by brockfanning** [comment]
@WohnungNDS Thank you for bringing it up - there seems to be a gap in our documentation, in regards to the necessary data repository configuration.

Try uncommenting and configuring this section: https://github.com/WohnungNDS/WK_Data/blob/develop/config_data.yml#L90

For a more detailed description of those options, you can see the parameters of the OutputGeojson file [here](https://github.com/open-sdg/sdg-build/blob/master/sdg/outputs/OutputGeoJson.py#L19).

But I think we do need to add something to the Maps documentation page about this.

**Comment by WohnungNDS** [comment]
@brockfanning I have tried different things:

the geojson in my data repository
```
map_layers:
  - geojson_file: https://github.com/WohnungNDS/WK_Data/geojson/maps/NI_Kurz_diss.geojson
    name_property: GEN
    id_property: AGS
    output_subfolder: maps
    filename_prefix: indicator
```_
Produces the following Error: 
yaml.parser.ParserError: while parsing a block collection
  in "config_data.yml", line 92, column 4
expected <block end>, but found '<block mapping start>'
  in "config_data.yml", line 93, column 5
##[error]Process completed with exit code 1.
```

```
map_layers:
 - geojson_file: https://wohnungnds.github.io/WK_Data/geojson/maps/NI_Kurz_diss.geojson
    name_property: GEN
    id_property: AGS
    output_subfolder: maps
    filename_prefix: indicator

produces the following error:

urllib.error.HTTPError: HTTP Error 404: Not Found
##[error]Process completed with exit code 1.
```


```
map_layers:
  - geojson_file: - geojson_file: https://christoph4711.github.io/open-sdg-site-starter/assets/maps/NI_Kurz_diss.geojson
    name_property: GEN
    id_property: AGS
    output_subfolder: maps
    filename_prefix: indicator
```_
```

no errors but also no map

It looks like the geojson file will not be found in the data repository....

but the geojson file seems to be valid as you can see [here](https://github.com/WohnungNDS/WK_Data/blob/develop/geojson/maps/NI_Kurz_diss.geojson)

**Comment by WohnungNDS** [comment]
@brockfanning Finally i tried this: 


```
map_layers:
  - geojson_file: https://wohnungnds.github.io/WK_Site/geojson/maps/NI_Kurz_diss.geojson
    name_property: GEN
    id_property: AGS
    output_subfolder: maps
    filename_prefix: indicator_
```
no errors, but also no map...

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS I've had a quick look and I;m not sure if you're missing something in your site repo config file - `subfolder` maybe?
Here's how the UK's map layers look in site repo:
https://github.com/ONSdigital/sdg-indicators/blob/develop/_config.yml#L137

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin 

my site config file:

```
map_options:
  minZoom: 5
  maxZoom: 10
  tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:  
    id: mapbox.light
    accessToken: pk.eyJ1IjoiY2hyaXN0b3BoNDcxMSIsImEiOiJjanp1cjdpbzQwMTFwM29tdzJ2ZTh3Ymo4In0.C7_7e3AFcMaF_QBg6MaT0Q
    attribution: <a href="https://www.mapbox.com">Mapbox</a> | <a href="http://www.bkg.bund.de">© GeoBasis-DE / BKG</a>
 

map_layers:

# The subfolder under 'geojson' in the data repository holding the GeoJSON files:
    subfolder: maps
    # The label to use in the "Download GeoJSON" button:
    label: indicator.map
    # The minimum zoom at which this layer should be visible.
    min_zoom: 0
    # The maximum zoom at which this layer should be visible.
    max_zoom: 20
    # Whether or not these boundaries should display statically on lower layers.
    staticBorders: false
```
subfolder exists....

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS apologies - missed that. What indicators are you expecting to see maps for?

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin 

https://wohnungnds.github.io/WK_Site/1-1-1/

and 

https://wohnungnds.github.io/WK_Site/1-2-1/

**Comment by brockfanning** [comment]
@WohnungNDS It's close, just a few issues:
1. For "geojson_file" [here](https://github.com/WohnungNDS/WK_Data/blob/develop/config_data.yml#L94), you can use a relative path: `geojson_file: geojson/maps/NI_Kurz_diss.geojson`. I notice you also have a copy in the root of the repository, so you could also do: `geojson_file: NI_Kurz_diss.geojson`
2. In `map_layers` there needs to be a `  -` on [this line](https://github.com/WohnungNDS/WK_Site/blob/develop/_config.yml#L142). That option is intended to be an "array" of map layers. For an example of the indentation see [here](https://open-sdg.readthedocs.io/en/latest/maps/#map_layers).

The fixes above should get the map to display. However I don't think any data will display, because I'm not sure if the GeoCodes in your data match the "AGS" codes in the geojson file. For example [here](https://github.com/WohnungNDS/WK_Data/blob/develop/data/indicator_1-1-1.csv#L49) Osterholz has K0356. But in the [geojson file](https://raw.githubusercontent.com/WohnungNDS/WK_Data/develop/geojson/maps/NI_Kurz_diss.geojson) if I search for "Osterholz" I see the code K03356.

**Comment by WohnungNDS** [comment]
@brockfanning 
Thank you so much, it works!
Yes i have some trouble with the GeoCodes, in the case of Osterloh. Osterloh an Göttingen have been merged in 2016. Before 2016 Osterloh was K03156 an Götting was K03152 after 2016 Göttingen becomes a new AGS 3159 ..... nevertheless K03356 is wrong

**Comment by WohnungNDS** [comment]
@brockfanning last question: what about the dissaggregation functionlity for maps? Is it implemented in 1.0.0? And if yes how do I use it?

**Comment by brockfanning** [comment]
No it's not in yet, but we do have a pull-request open about it [here](https://github.com/open-sdg/open-sdg/pull/663). If you're interested in trying it out we would welcome the feedback. To use it you just point to that remote/branch instead, in your _config.yml file. So instead of `remote_theme: open-sdg/open-sdg@1.0.0` you would have `remote_theme: brockfanning/open-sdg@map-disaggregation-select`.

Also just to be clear, if you wanted to clean up now that maps are working, you could delete both of these folders:
* https://github.com/WohnungNDS/WK_Data/tree/develop/geojson/maps
* https://github.com/WohnungNDS/WK_Site/tree/develop/geojson/maps

**Comment by WohnungNDS** [comment]
Great, I will have look on this tomorrow!

**Comment by WohnungNDS** [comment]
Hi @brockfanning 

at the first glance it works great. Have look [here](https://wohnungnds.github.io/WK_Site/1-1-1/#mapview). 

The dropdown menue contains the two dissaggregation categories 1 Zimmer and 2 Zimmer but also "Stade" which is one of the cities or regions you can select also....
I have no Idea why "Stade" is also in the dropdown menue, I may understand that if it will be "Ammerland" because it's the first row in thee table..

The values if you select "1 Zimmer" or "2 Zimmer" on the map are dispplayed correct

![grafik](https://user-images.githubusercontent.com/67795376/87154178-09f4d500-c2b9-11ea-8c76-4f2c549576d3.png)

**Comment by brockfanning** [comment]
Thanks very much for the feedback @WohnungNDS. I'll copy your notes over to #374.

The problem with "Stade" is I think because it assumes that each region on the map carries the same set of disaggregations, and so it randomly picks one (which happened to be Stade). But in this case you have a column for the name of the region (which makes sense). A quick fix might be to "exclude" that column from the geojson. To try this, you can add one more parameter after [this line](https://github.com/WohnungNDS/WK_Data/blob/develop/config_data.yml#L98). Try adding:

```
exclude_columns: ['Gebietseinheit']
```

So the whole thing would be:

```
map_layers:
  - geojson_file: NI_Kurz_diss.geojson
    name_property: GEN
    id_property: AGS
    output_subfolder: maps
    filename_prefix: indicator_
    exclude_columns: ['Gebietseinheit']
```
