### ISSUE TITLE
data_star_value does have no effekt

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#775]
**Please complete the following information** 
Site repository URL: [https://github.com/WohnungNDS/WK_Site](https://github.com/WohnungNDS/WK_Site)
Open SDG version: [e.g. 1.0.0]

**Describe the bug**
data_start_values does not work

finde my meta data file  [here](https://github.com/WohnungNDS/WK_Data/edit/develop/meta/1-1-1.md)

```
data_start_values:
  field: Gebietseinheit
  value: Niedersachsen
```
The [Indicator 1.1.1](https://wohnungnds.github.io/WK_Site/1-1-1/) still starts with "Ammerland" instead of "Niedersachsen"

![grafik](https://user-images.githubusercontent.com/67795376/87430916-2c069400-c5e6-11ea-9ff8-49e72105f751.png)

**Comment by MoBosse** [comment]
Could you try to add 
 ```
field: Kategorien
 value: Bestand_Jahresbeginn
``` 

below the other start_value?

**Comment by brockfanning** [comment]
The structure of that particular metadata field is expected to be an array of hashes (in Ruby terms) which in YAML would look like this:

```
data_start_values:
  - field: my_field
    value: my_value
  - field: my_other_field
    value: my_other_value
```

So I think it's the dashes that are needed.

Note that the following is also valid and would behave the same:

```
data_start_values:
  -
    field: my_field
    value: my_value
  -
    field: my_other_field
    value: my_other_value
```
